planning/urls.py
from django.urls import path

from .feeds import TourFeed
from .views import (
    HomeView,
    TourDetailView,
    TourListView,
    email_week_planning_pdf,
    week_planning,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("tours", TourListView.as_view(), name="tours"),
    path("tours/<int:pk>", TourDetailView.as_view(), name="tour_detail"),
    path("cal/feed.ics", TourFeed(), name="feed"),
    path("cal/<int:pk>/feed.ics", TourFeed(), name="personnal_feed"),
    path("email_pdf", email_week_planning_pdf, name="send_mail"),
    path(
        "email_pdf/<str:moment>",
        email_week_planning_pdf,
        name="send_mail_moment",
    ),
    path("pdf/<str:moment>", week_planning, name="week_planning_moment"),
    path("pdf", week_planning, name="week_planning"),
]

settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# if settings.REGISTRATION_APPROVAL:
#     registration_include = "registration.backends.admin_approval.urls"
# else:
#     registration_include = "registration.backends.default.urls"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("planning.urls")),
    path("", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

users/urls.py
from django.urls import path

from .views import AuthUserDetail

urlpatterns = [
    path("accounts/profile/", AuthUserDetail.as_view(), name="my-profile")
]

planning/models.py
import datetime
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class BaseModel(models.Model):
    """Generic base model with standard metadatas"""

    timestamp_create = models.DateTimeField(auto_now_add=True, editable=False)
    timestamp_update = models.DateTimeField(auto_now=True, editable=False)
    created_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        db_index=True,
        editable=False,
        related_name="+",
        on_delete=models.SET_NULL,
    )
    updated_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        db_index=True,
        editable=False,
        related_name="+",
        on_delete=models.SET_NULL,
    )

    class Meta:
        abstract = True


class Kid(BaseModel):
    name = models.CharField(
        max_length=100, blank=False, null=False, verbose_name=_("name")
    )
    referent = models.ManyToManyField(
        User, verbose_name=_("fathers"), related_name="kids"
    )

    def __str__(self):
        return self.name


# Create your models here.
class Tour(BaseModel):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    start = models.DateTimeField(
        blank=False, null=False, verbose_name=_("start")
    )
    end = models.DateTimeField(blank=True, null=True, verbose_name=_("end"))
    companion = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name="tours",
        on_delete=models.SET_NULL,
        verbose_name=_("companion"),
        name="companion",
    )
    kids = models.ManyToManyField(Kid, verbose_name=_("kid"), blank=True)

    @property
    def kids_count(self):
        """Returns kids count for each tour

        Returns:
            int: Number of kids
        """
        return self.kids.count()

    @property
    def title(self):
        return _(f"{self.companion or '!!!'} {str(self.kids_count)} kids")

    @property
    def day_time(self):
        """Returns kids count for each tour

        Returns:
            int: Number of kids
        """
        return (
            _("morning")
            if self.start.time() < datetime.time(12)
            else _("afternoon")
        )

    def __str__(self):
        return str(self.start.date())

    def get_absolute_url(self):
        return reverse("tour_detail", kwargs={"pk": self.pk})

planning/forms.py
from django import forms

from .models import Tour


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = ["companion", "kids"]
        widgets = {
            "kids": forms.CheckboxSelectMultiple,
        }

    # def __init__(self, *args, **kwargs):
    #     self.user = kwargs.pop(
    #         "user"
    #     )  # To get request.user. Do not use kwargs.pop('user', None) due to potential security hole

    #     super().__init__(*args, **kwargs)
    #     self.fields["kids"].queryset = Kid.objects.filter(referent=self.user).all()


# class SubscribeKidsForm(forms.Form):
#     tours = forms.MultipleChoiceField(
#         widget=forms.CheckboxSelectMultiple, choices=Tour.objects.all()
#     )
#     kids = forms.MultipleChoiceField(
#         widget=forms.CheckboxSelectMultiple, choices=Kid.objects.all()
#     )

planning/views.py
import datetime
from typing import Any

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView, UpdateView
from django_filters.views import FilterView

from .filters import TourFilter
from .forms import TourForm
from .models import Kid, Tour
from .pdf import pdf_week_planning
from .utils import week_magic

User = get_user_model()


def default_time_filter() -> datetime:
    """Get default time filter (morning or afternoon tours)

    Returns:
        datetime: datetime filter
    """
    now = datetime.datetime.now()
    hour = 0 if now.hour < 12 else 12
    result = now.replace(hour = hour, minute=0, second=0, microsecond=0)
    return result


def datetime_interval(months: int) -> datetime:
    """calculate future date from month interval

    Args:
        months (int): Number of months

    Returns:
        datetime: Future date (in n months)
    """
    today = datetime.datetime.now()
    delta = datetime.timedelta(days=months * 365 / 12)
    return today + delta


class GenericTourListView(LoginRequiredMixin, FilterView):
    model = Tour
    template_name = "tour_list.html"
    queryset = (
        Tour.objects.order_by("start")
        .select_related("companion")
        .prefetch_related("kids")
    )
    filterset_class = TourFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["kids"] = Kid.objects.all()
        return context


class HomeView(GenericTourListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Next tours")
        context["home"] = True
        return context

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        date = default_time_filter()
        return qs.filter(start__gte=date).filter(
            start__lte=datetime_interval(3)
        )


class TourListView(GenericTourListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("All tours")
        context["kids"] = Kid.objects.all()

        # context["now"] = datetime.datetime.now()
        return context


class TourDetailView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Tour
    template_name = "tour_detail.html"
    # fields = ["companion", "kids"]
    form_class = TourForm
    success_url = reverse_lazy("home")
    success_message = _("Your update have been successfully saved")
    queryset = Tour.objects.select_related("companion").prefetch_related(
        "kids"
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["companions"] = User.objects.all()
        context["kids"] = Kid.objects.all()
        # context["self_kids"] = serializers.serialize(
        #     "json",
        #     Kid.objects.filter(referent=user).all()
        #     if not (user.is_superuser or user.is_staff)
        #     else Kid.objects.all(),
        # )

        return context


class CalendarView(LoginRequiredMixin, TemplateView):
    template_name = "calendar.html"


def week_planning(request, moment: str = None):
    print(moment)
    if moment and moment == "next":
        d = datetime.datetime.today() + datetime.timedelta(days=7)
    else:
        d = datetime.datetime.today()
    response = HttpResponse(content_type="application/pdf")
    file_date = datetime.datetime.today().strftime("%Y-%m-%d")
    response["Content-Disposition"] = f"inline; filename={file_date}.pdf"
    date_min, date_max = week_magic(d.date())
    data = Tour.objects.filter(
        start__gte=date_min, start__lte=date_max
    ).order_by("start")
    pdf = pdf_week_planning(request, data, date_min, date_max)
    response.write(pdf)
    return response


def email_week_planning_pdf(request, moment: str = None):
    if moment == "next":
        d = datetime.datetime.today() + datetime.timedelta(days=7)
    else:
        d = datetime.datetime.today()
    date_min, date_max = week_magic(d.date())
    data = Tour.objects.filter(
        start__gte=date_min, start__lte=date_max
    ).order_by("start")
    pdf = pdf_week_planning(request, data, date_min, date_max)
    subject = f"{settings.EMAIL_SUBJECT_PREFIX} Planning de la semaine {'prochaine' if moment == 'next' else '' }"
    message = f"""Bonjour,

Veuillez trouver en PJ le planning de bus scolaire pour {'la semaine à venir' if moment == 'next' else 'cette semaine' }

Bien cordialement,

Toute l'équipe
{settings.SITE_NAME}
"""
    mail = EmailMessage(
        subject, message, settings.EMAIL_HOST_USER, settings.PDF_EMAILS
    )
    mail.attach("bus_planning.pdf", pdf, "application/pdf")

    try:
        mail.send(fail_silently=False)
        return HttpResponse("Mail Sent")
    except Exception as e:
        return HttpResponse(f"Mail Not Sent : {str(e)}")

planning/templates/calendar.html
{% extends 'base.html' %} {% block more_assets %}
<script
  src="https://cdn.jsdelivr.net/npm/fullcalendar/index.global.min.js"
  defer
></script>
{% endblock %} {% block content %}

<div id="calendar"></div>

{% endblock %} {% block script %}

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const calendarEl = document.getElementById("calendar");
    const calendar = new FullCalendar.Calendar(calendarEl, {
      timeZone: "Europe/Paris",
      initialView: "listWeek",
      windowResize: function (view) {
        console.log(this);
        if (window.outerWidth < 514) {
          calendarEl.fullCalendar("changeView", "basicDay");
        } else {
          calendarEl.fullCalendar("changeView", "month");
        }
      },
      eventDidMount(arg) {
        console.debug(arg);
      },
      eventSources: [
        {
          url: "{% url 'tour-list' %}", // use the `url` property
          color: "green",
          textColor: "black", // an option!
        },
      ],
    });
    calendar.render();
  });
</script>
{% endblock %}

planning/templates/nobody_alert.html
{% load i18n %}

<span class="text-danger">
  <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512">
    <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
    <path
      d="M112 48a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm40 304V480c0 17.7-14.3 32-32 32s-32-14.3-32-32V256.9L59.4 304.5c-9.1 15.1-28.8 20-43.9 10.9s-20-28.8-10.9-43.9l58.3-97c17.4-28.9 48.6-46.6 82.3-46.6h29.7c33.7 0 64.9 17.7 82.3 46.6l44.9 74.7c-16.1 17.6-28.6 38.5-36.6 61.5c-1.9-1.8-3.5-3.9-4.9-6.3L232 256.9V480c0 17.7-14.3 32-32 32s-32-14.3-32-32V352H152zM432 224a144 144 0 1 1 0 288 144 144 0 1 1 0-288zm0 240a24 24 0 1 0 0-48 24 24 0 1 0 0 48zm0-192c-8.8 0-16 7.2-16 16v80c0 8.8 7.2 16 16 16s16-7.2 16-16V288c0-8.8-7.2-16-16-16z"
    /></svg
  >&nbsp;{% trans 'Personne' %}
</span>

planning/templates/subscribe_kids.html
{% extends 'base.html' %} {% load static i18n l10n %} {% block content %}
<div class="content">
  <form class="box" method="post">
    <h1>Connexion</h1>
    {% csrf_token %} {{form.as_div}}
    <button
      class="button is-rounded is-primary"
      type="submit"
      name="button"
      type="submit"
    >
      Enregistrer
    </button>
  </form>
</div>
{% endblock %} {% block script %} {% endblock %}

planning/templates/tour_detail.html
{% extends 'base.html' %} {% block content %}
    <div class="panel">
        <div class="panel-heading">
            <strong>{{ object.start|date:'l d N Y' }}</strong>&nbsp;
            <span
                    class="tag is-{% if object.day_time|safe == _('morning') %}primary{% else %}warning{% endif %}"
            >{{ object.start | date:"A" }}</span>
        </div>
        <div class="panel-block">
            <div class="content">
                <p>
                    {% if object.kids.count > 0 and object.companion %}
                        <svg
                                xmlns="http://www.w3.org/2000/svg"
                                height="1em"
                                viewBox="0 0 512 512"
                        >
                            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                            <path
                                    style="fill: #2ec27e"
                                    d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"
                            />
                        </svg>
                    {% elif object.kids.count > 0 and not object.companion %}
                        <svg
                                xmlns="http://www.w3.org/2000/svg"
                                height="1em"
                                viewBox="0 0 512 512"
                        >
                            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                            <path
                                    style="fill: #e01b24"
                                    d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"
                            />
                        </svg>
                    {% else %}
                        <svg
                                xmlns="http://www.w3.org/2000/svg"
                                height="1em"
                                viewBox="0 0 448 512"
                        >
                            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                            <path
                                    style="fill: #c0bcbf"
                                    d="M0 96C0 60.7 28.7 32 64 32H384c35.3 0 64 28.7 64 64V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96z"
                            />
                        </svg>
                    {% endif %}
                    <strong
                            class="{% if object.kids.count > 0 and not object.companion %}has-text-danger-dark{% endif %}"
                    >{{ object.companion.get_full_name|default:"Personne!!!" }}</strong
                    >{% if object.companion %}
                    <small>@{{ object.companion }}</small>
                {% endif %}
                    <span
                            class="tag is-{% if object.kids.count %}primary{% else %}disable{% endif %}"
                    >{{ object.kids.count }}</span
                    >
                </p>
                <p>
                    {% for kid in kids %}
                        <span
                                class="tag {% if kid in object.kids.all %}is-link is-medium{% else %}is-normal{% endif %}"
                        >{{ kid.name }}{% if kid in object.kids.all %}{% endif %}</span
                        >
                    {% endfor %}
                </p>
            </div>
        </div>
        <form action="" method="post">
            <div class="panel-block">
                {% csrf_token %}
                <div class="content">
                    <h2>Modifier</h2>
                    <div class="field">
                        <label class="label" for="id_companion">Accompagnateur</label>
                        <div class="control">
                            <div class="select">{{ form.companion }}</div>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label" for="id_companion">Enfants</label>
                        <div class="control">{{ form.kids }}</div>
                    </div>
                </div>
            </div>
            <div class="panel-block">
                <input class="button is-rounded is-primary is-fullwidth" name="button" type="submit"/>
            </div>
        </form>
    </div>
{% endblock %} {% block script %}
{% endblock %}
{% block style %}


{% endblock %}

planning/templates/tour_list.html
{% extends 'base.html' %} {% load static i18n l10n %} {% block content %}
<div class="content">
  <nav
    class="panel fullheight"
  >
    <p class="panel-heading" style="margin-bottom: unset !important">
      {{title}} {% if home %}<a
        class="button is-info is-rounded is-light is-small"
        href="{% url 'tours' %}"
      >
        {% trans "See all year" %} </a
      >{% endif %}
      <button
        class="js-modal-trigger button is-rounded is-small is-info"
        data-target="filter-tours-modal"
      >
        {% trans "Filtering" %}</button
      >{% if filter.is_bound %}
      <a class="button is-rounded is-small is-danger" href="{% url 'tours' %}"
        >{% trans "Clear filters" %}
      </a>
      {% endif %}
    </p>
    <div id="filter-tours-modal" class="modal">
      <div class="modal-background"></div>
      <div class="modal-card">
        <form method="get">
          <header class="modal-card-head">
            <p class="modal-card-title">Filtrer les tournées</p>
            <button class="delete is-danger" aria-label="close"></button>
          </header>
          <section class="modal-card-body">
            <div class="field">
              <label class="label" for="id_companion">Accompagnateur</label>
              <div class="control">
                <div class="select">{{filter.form.companion}}</div>
              </div>
            </div>
            <div class="field">
              <label class="label" for="id_companion">Enfants</label>
              <div class="control">{{filter.form.kids}}</div>
            </div>
          </section>
          <footer class="modal-card-foot">
            <input class="button is-primary" type="submit" />
            <button class="button is-danger">Cancel</button>
          </footer>
        </form>
      </div>
    </div>
    <div
      style="
        height: calc(100% - 55px);
        max-height: 100% !important;
        overflow: auto;
      "
    >
      {% for tour in filter.qs %}
      <div
        class="panel-block {% if tour.kids.count > 0 and not tour.companion %} has-background-danger-light {% elif tour.kids.count > 0 and tour.companion %} has-background-primary-light {% else %} has-background-info-light {% endif %}"
      >
        <div class="column">
          <a href="{% url 'tour_detail' pk=tour.pk %}" title="Modifier">
            {% if tour.kids.count > 0 and tour.companion %}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              height="1em"
              viewBox="0 0 512 512"
            >
              <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
              <path
                style="fill: #2ec27e"
                d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"
              />
            </svg>
            {% elif tour.kids.count > 0 and not tour.companion %}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              height="1em"
              viewBox="0 0 512 512"
            >
              <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
              <path
                style="fill: #e01b24"
                d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"
              />
            </svg>
            {% else %}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              height="1em"
              viewBox="0 0 448 512"
            >
              <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
              <path
                style="fill: #c0bcbf"
                d="M0 96C0 60.7 28.7 32 64 32H384c35.3 0 64 28.7 64 64V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96z"
              />
            </svg>
            {% endif %}

            <strong>{{tour.start | date:"l d N Y"}}</strong>&nbsp;
            <span
              class="tag is-{% if tour.day_time|safe == _('morning') %}primary{% else %}warning{%endif%}"
              >{{tour.start | date:"A"}}</span
            >
          </a>
        </div>
        <div class="column">
          <strong
            class="{% if tour.kids.count > 0 and not tour.companion %}has-text-danger-dark{% endif %}"
            >{{tour.companion.get_full_name|default:"Personne!!!" }}</strong
          >{% if tour.companion %}
          <small>@{{tour.companion}}</small>
          {% endif %}
          <span
            class="tag is-{% if tour.kids.count %}primary{% else %}disable{%endif%} js-modal-trigger"
            data-target="modal-js-{{tour.pk}}"
            >{{ tour.kids.count }}</span
          >
        </div>
      </div>
      <div id="modal-js-{{tour.pk}}" class="modal">
        <div class="modal-background"></div>

        <div class="modal-content">
          <div class="box">
            <h1>{{tour.kids.count}}/{{kids.count}} enfants</h1>
            {% for kid in kids %}
            <span
              class="tag {% if kid in tour.kids.all %}is-link is-medium{% else %}is-normal{%endif%}"
              >{{kid.name}}{% if kid in tour.kids.all %}{% endif%}</span
            >
            {%endfor%}
            <!-- Your content -->
          </div>
        </div>

        <button class="modal-close is-large" aria-label="close"></button>
      </div>
      {% endfor %}
    </div>
  </nav>
</div>

{% endblock %} {% block script %}
<script></script>
{% endblock %}
{% block style %}
    <style>
      .fullheight {
        height: calc(100vh - 150px);
        max-height: 100% !important;
      }
      @media screen and (max-width: 640px) {
        .custom-section {
          padding:0;
        }
        .fullheight {
          height: calc(100vh - 3.5rem);
          max-height: 100% !important;
          overflow-y: hidden;
        }
      }
    </style>

{% endblock %}